export const filterData = [
  {
    placeholder: "Minimum Experience",
    property: "minExp",
    options: [
      { label: 1, value: 1 },
      { label: 2, value: 2 },
      { label: 3, value: 3 },
      { label: 4, value: 4 },
      { label: 5, value: 5 },
      { label: 6, value: 6 },
      { label: 7, value: 7 },
      { label: 8, value: 8 },
      { label: 9, value: 9 },
      { label: 10, value: 10 },
    ],
    width: 200,
  },
  {
    placeholder: "Role Type",
    property: "location",
    options: [
      { label: "Remote", value: "remote" },
      { label: "In-Office", value: "in-office" },
    ],
    width: 150,
  },
  {
    placeholder: "Minimum Base Pay Salary",
    property: "minJdSalary",
    options: [
      { label: "0L", value: "0" },
      { label: "10L", value: "10" },
      { label: "20L", value: "20" },
      { label: "30L", value: "30" },
      { label: "40L", value: "40" },
      { label: "50L", value: "50" },
      { label: "60L", value: "60" },
      { label: "70L", value: "70" },
    ],
    width: 250,
  },
  {
    placeholder: "Role",
    property: "jobRole",
    options: [
      { label: "Frontend Developer", value: "frontend" },
      { label: "IOS Developer", value: "ios" },
      { label: "Android Developer", value: "android" },
      { label: "Tech Lead", value: "tech lead" },
      { label: "Backend Developer", value: "backend" },
    ],
    width: 150,
  },
];
